version: '3.5'
services:
  zipkin-server:
    image: rsakin/zipkin-server
    build:
      context: ./zipkin-server
      dockerfile: Dockerfile
    ports:
      - "9411:9411"

  zipkin-service-1:
    image: rsakin/zipkin-service-1
    build:
      context: ./zipkin-service-1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    links:
      - zipkin-server

  zipkin-service-2:
    image: rsakin/zipkin-service-2
    build:
      context: ./zipkin-service-2
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - zipkin-server

  zipkin-service-3:
    image: rsakin/zipkin-service-3
    build:
      context: ./zipkin-service-3
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    links:
      - zipkin-server

  zipkin-service-4:
    image: rsakin/zipkin-service-4
    build:
      context: ./zipkin-service-4
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    links:
      - zipkin-server